require('dotenv').config(); 
const express = require('express'); 
const cors = require('cors'); 
const multer = require('multer'); 
const { GoogleGenAI } = require('@google/genai'); 

// ================================ 
// 1. Initialize Express 
// ================================ 
const app = express(); 
const PORT = process.env.PORT || 5001; 

app.use(cors()); 
app.use(express.json()); 

// ================================ 
// 2. Configure multer for uploads 
// ================================ 
const storage = multer.memoryStorage(); 
const upload = multer({ 
    storage, 
    limits: { fileSize: 10 * 1024 * 1024 }, // 10 MB 
    fileFilter: (req, file, cb) => {
        if (file.mimetype.startsWith('image/')) {
            cb(null, true);
        } else {
            cb(new Error('Only image files are allowed'), false);
        }
    }
}); 

// ================================ 
// 3. Initialize Google GenAI 
// ================================ 
const genAI = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY }); 

// ================================ 
// 4. Helper functions 
// ================================ 
function fileToGenerativePart(buffer, mimeType) { 
    return { 
        inlineData: { 
            data: buffer.toString('base64'), 
            mimeType 
        } 
    }; 
} 

function getStylePrompt(style) { 
    const stylePrompts = { 
        "Anime Style": "Using the provided image of this person, transform this portrait into pretty, anime style.", 
        "Picasso Style": "Using the provided image of this person, transform this portrait into Picasso painting style.", 
        "Oil Painting Style": "Using the provided image of this person, transform this portrait into the style of a Degas oil painting.", 
        "Frida Kahlo Style": "Using the provided image of this person, transform this portrait into Frida Kahlo painting style.", 
        "Miniature Effect": "Create a 1/7 scale commercialized figure of the character in the illustration, in a realistic style and environment. Place the figure on a computer desk, using a circular transparent acrylic base without any text. On the computer screen, display the ZBrush modeling process of the figure. Next to the computer screen, place a BANDAI-style toy packaging box printed with the original artwork." 
    }; 
    return stylePrompts[style] || stylePrompts["Anime Style"]; 
} 

// ================================ 
// 5. API endpoint 
// ================================ 
app.post('/api/transform', upload.single('image'), async (req, res) => { 
    try { 
        if (!req.file) {
            return res.status(400).json({ success: false, message: 'No image uploaded' });
        }

        const style = req.body.style || 'Anime Style'; 
        const stylePrompt = getStylePrompt(style); 

        console.log(`🎨 Transforming image with style: ${style}`);
        console.log(`📝 Style prompt: ${stylePrompt}`);

        // Use Gemini 2.5 Flash for image generation
        const response = await genAI.models.generateContent({
            model: "gemini-2.5-flash-image-preview",
            contents: [
                fileToGenerativePart(req.file.buffer, req.file.mimetype),
                { text: stylePrompt }
            ],
            generationConfig: {
                temperature: 0.7,
                topK: 40,
                topP: 0.95,
                maxOutputTokens: 2048,
            }
        });

        // Extract image from response
        const candidates = response.candidates;
        if (!candidates || candidates.length === 0) {
            throw new Error('No transformation result from Gemini API');
        }

        const content = candidates[0].content;
        const parts = content.parts || [];
        
        // Look for image parts in the response
        const imagePart = parts.find(part => part.inlineData && part.inlineData.mimeType.startsWith('image/'));
        
        if (!imagePart) {
            console.log('Available parts:', parts.map(p => ({ type: p.inlineData ? 'image' : 'text', mimeType: p.inlineData?.mimeType })));
            throw new Error('No image generated by Gemini API');
        }

        const transformedImageData = imagePart.inlineData.data;
        const outputMimeType = imagePart.inlineData.mimeType;

        console.log(`✅ Transformation successful! Output format: ${outputMimeType}`);

        return res.status(200).json({ 
            success: true, 
            transformedImage: transformedImageData, 
            mimeType: outputMimeType,
            style: style,
            prompt: stylePrompt,
            message: `Image successfully transformed with ${style} style!`
        }); 

    } catch (error) { 
        console.error('❌ Error transforming image:', error); 
        return res.status(500).json({ 
            success: false, 
            message: 'Error transforming image: ' + error.message, 
            error: error.message 
        }); 
    } 
}); 

// Health check endpoint
app.get('/api/health', (req, res) => {
    res.json({ status: 'ok', timestamp: new Date().toISOString() });
});

// ================================ 
// 6. Start server 
// ================================ 
app.listen(PORT, () => console.log(`🚀 Server running on port ${PORT}`));